[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "mychat"
version = "0.1.0"
description = "CLI based LLM chat application"
requires-python = ">=3.11"

dependencies = [
    "openai",
    "typer",
    "rich",
    "python-dotenv"
]

[project.scripts]
mychat = "mychat.cli:app"

[tool.setuptools.packages.find]
where = ["src"]