trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0

  - script: |
      echo "Github Repository:"
      git remote -v

      echo "GitHub Current Branch:"
      git branch --show-current

      echo "Configuring Azure DevOps Git Credentials..."
      git remote remove ado 2>/dev/null || true
      
      git remote add ado \
        https://dev.azure.com/hraverkar/Sample/_git/LLM-Chat-Cli
      
      echo "Pushing to Azure DevOps..."
      git push ado HEAD:refs/heads/main

    displayName: 'Push to Azure DevOps'